Development
cyneptic/letsgo_smspanel pull request #5
Opened 2023-07-03 12:30 UTC by amir62hossein

2023-07-03 15:01 UTC, cyneptic requested changes

2023-07-03 15:01 UTC, cyneptic commented on controller/wallet_handler.go
> +	e.GET("/walletCredit" , walletHandler.HasWalletCreditHandler)
1. do not use camelCase in endpoint naming, either do lowercase or lowercase with hyphens ("createwallet", "create-wallet")
2. maybe do "wallet-create" intead of "create-wallet" to be consistent
3. "wallet-credit" is not a good name in relation to what it does, try something better maybe "wallet-can-afford" or "wallet-has-amount" or something similar.

2023-07-03 15:01 UTC, cyneptic commented on controller/wallet_handler.go
> +	}
validation should go in validators.

2023-07-03 15:01 UTC, cyneptic commented on controller/wallet_handler.go
> +	}
validation should go in validators

2023-07-03 15:01 UTC, cyneptic commented on controller/wallet_handler.go
> +	}
validation should go in validators.

2023-07-03 15:01 UTC, cyneptic commented on controller/wallet_handler.go
> +	}
validation should go in validators.

2023-07-03 15:01 UTC, cyneptic commented on infrastructure/repository/wallet.go
> +func (r *PGRepository) GenerateWalletRepository(wallet entities.Wallet) error {
Using repository in the function name makes one thing you are creating a wallet repository not a wallet entity within the repository
"GenerateWallet" or "CreateWallet" is better.

2023-07-03 15:01 UTC, cyneptic commented on infrastructure/repository/wallet.go
> +func (r *PGRepository) ChargeWalletRepository(walletID , userID uuid.UUID , amount int)  error {
Using repository in the function name makes one thing you are charing a wallet repository not a wallet entity within the repository
"ChargeWallet" is better.

2023-07-03 15:01 UTC, cyneptic commented on infrastructure/repository/wallet.go
> +func (r *PGRepository) GetWalletAmountRepository(walletID  uuid.UUID) (*entities.Wallet, error) {
if this function is returning a wallet it should be named "GetWallet" not "GetWalletAmount"

2023-07-03 15:01 UTC, cyneptic commented on infrastructure/repository/wallet.go
> +func (r *PGRepository) HasEnoughCreditRepository(walletID uuid.UUID) (*entities.Wallet, error) {
if this function is returning a wallet it should be named "GetWallet" not "HasEnoughCredit"

2023-07-03 15:01 UTC, cyneptic commented on .idea/.gitignore
should this file be included?

2023-07-03 15:01 UTC, cyneptic commented on .idea/vcs.xml
should this file be included?

2023-07-03 15:01 UTC, cyneptic commented on .idea/modules.xml
should this file be included?

2023-07-03 15:01 UTC, cyneptic commented on .idea/letsgo_smspanel.iml
should this file be included?

2023-07-03 15:01 UTC, cyneptic commented on controller/contact_handlers.go
revert the changes to someone else's file there is no need to delete these spaces. specially if you are not the author of the code.

2023-07-03 15:01 UTC, cyneptic commented on internal/core/service/wallet_service.go
> +
should check if amount is a proper positive value, it could be negative

2023-07-05 15:48 UTC, amir62hossein commented
Meo Meo

2023-07-06 13:03 UTC, cyneptic approved these changes
lgtm

2023-07-06 13:03 UTC, merged