Development
cyneptic/letsgo_smspanel pull request #6
Opened 2023-07-05 06:57 UTC by DanialAbedini

check it and tell me if anythings wrong

2023-07-05 13:59 UTC, cyneptic requested changes
ContactList is the same as PhoneBook struct.
every user has their own list of phonebooks.
what has happened here is that you are taking all the contacts whenever you are using contactlist.
what we need is to take a specific PhoneBook from a User and send the message to all Contacts of That PhoneBook of that User.

2023-07-05 13:59 UTC, cyneptic commented on controller/sendsms_handler.go
> +func NewSnedSMSHandler() *SendSMSHandler {
I think there's a typo here, Send is written as Sned.

2023-07-05 13:59 UTC, cyneptic commented on controller/sendsms_handler.go
> +	e.POST("/sendcontactlistinterval", handler.SendToContactListIntervalHandler)
its hard to read lowercase addresses when they have multiple words, I suggest using hyphens (-) to put some space between the words.
i.e:
send-message-list
send-message-user
send-message-number
send-message-interval

2023-07-05 13:59 UTC, cyneptic commented on controller/sendsms_handler.go
> +	return c.String(http.StatusOK, "Fine")
I don't think "fine" is a good response to a user requesting a message.
I suggest maybe returning a more suitable message or nothing at all, http.StatusOK should be enough.

2023-07-05 13:59 UTC, cyneptic commented on controller/sendsms_handler.go
> +	return c.String(http.StatusOK, "Fine")
I don't think "fine" is a good response to a user requesting a message.
I suggest maybe returning a more suitable message or nothing at all, http.StatusOK should be enough.

2023-07-05 13:59 UTC, cyneptic commented on controller/sendsms_handler.go
> +	return c.String(http.StatusOK, "Fine")
I don't think "fine" is a good response to a user requesting a message.
I suggest maybe returning a more suitable message or nothing at all, http.StatusOK should be enough.

2023-07-05 13:59 UTC, cyneptic commented on controller/sendsms_handler.go
> +	return c.String(http.StatusOK, "Fine")
I don't think "fine" is a good response to a user requesting a message.
I suggest maybe returning a more suitable message or nothing at all, http.StatusOK should be enough.

2023-07-05 13:59 UTC, cyneptic commented on controller/validators/sendsms_validator.go
> +func ValidateNumber(p string) (time.Duration, error) {
this function conflicts with single responsibility principle and its name is not suitable
a validator function should only validate but its converting values to time.
"ValidateNumber" means its validating a number when in fact its validating a time. and its also making a converstion to time.

I suggest making helpers to help out with the conversion and renaming the function properly.

2023-07-05 13:59 UTC, cyneptic commented on controller/validators/sendsms_validator.go
> +func ValidatorReciveMessage(msg entities.MessageReciver) (entities.Message, error) {
typo in function name "Receive" is written as "Recive"

2023-07-05 13:59 UTC, cyneptic commented on internal/core/entities/base.go
> +	ID         uuid.UUID `gorm:"primaryKey;type:uuid;Column:id" json:"id"`
Column is used when the name defined in the struct is different than the name of the column. in this case there is no need for this.

I suggest undoing all unnecessary changes to the files that you are not the author of.

2023-07-05 13:59 UTC, cyneptic commented on internal/core/entities/base.go
> +	DeletedAt  *gorm.DeletedAt
I suggest undoing all unnecessary changes to the files that you are not the author of.

2023-07-05 13:59 UTC, cyneptic commented on internal/core/entities/number.go
> +	UserId           uuid.UUID `gorm:"Column:userid;type:uuid" json:"user_id"`
user_id is the best practice we tend to separate different words with underscore in databases and json.

2023-07-07 17:20 UTC, cyneptic commented
I need the conflicts resolved in order to review the entire request, please resolve the conflicts.

2023-07-08 10:22 UTC, closed without merging

2023-07-08 17:28 UTC, DanialAbedini commented
open branch

2023-07-08 17:28 UTC, DanialAbedini commented
open development

2023-07-08 17:30 UTC, DanialAbedini commented
open agian

2023-07-08 17:31 UTC, DanialAbedini commented
open branch